// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var maxeeCompanies = MaxeeCompanies.FromJson(jsonString);
using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Maxee.DemoAPIConsole.MaxeeCompaniesQuickType
{
    public partial class MaxeeCompanies
    {
        [JsonProperty("data")]
        public Datum[] Data { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("aggregateResults")]
        public object AggregateResults { get; set; }

        [JsonProperty("errors")]
        public object Errors { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("status")]
        public bool Status { get; set; }

        [JsonProperty("sequence")]
        public long Sequence { get; set; }

        [JsonProperty("divisions")]
        public object[] Divisions { get; set; }

        [JsonProperty("companyUserRoles")]
        public CompanyUserRole[] CompanyUserRoles { get; set; }

        [JsonProperty("insertedBy")]
        public string InsertedBy { get; set; }

        [JsonProperty("insertedOn")]
        public DateTimeOffset InsertedOn { get; set; }

        [JsonProperty("updatedBy")]
        public object UpdatedBy { get; set; }

        [JsonProperty("updatedOn")]
        public object UpdatedOn { get; set; }
    }

    public partial class CompanyUserRole
    {
        [JsonProperty("companyId")]
        public long CompanyId { get; set; }

        [JsonProperty("userId")]
        public Guid UserId { get; set; }

        [JsonProperty("roleId")]
        public Guid RoleId { get; set; }
    }

    public partial class MaxeeCompanies
    {
        public static MaxeeCompanies FromJson(string json) => JsonConvert.DeserializeObject<MaxeeCompanies>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MaxeeCompanies self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}